## 预备知识

### 环境配置
  配置清华PyPI镜像（如无法运行，将pip版本升级到>=10.0.0）
  pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

### pytorch的数据操作

#### 创建Tensor

In [1]:
import torch

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
x = torch.empty(5, 3)
x
import numpy as np
idx = np.arange(0, 10)
idx
torch.randperm(8)

tensor([[7.9468e+01, 4.5625e-41, 7.9468e+01],
        [4.5625e-41, 2.1200e-04, 4.5625e-41],
        [2.1200e-04, 4.5625e-41, 2.1055e-04],
        [4.5625e-41, 2.1200e-04, 4.5625e-41],
        [2.1054e-04, 4.5625e-41, 2.1076e-04]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([0, 2, 7, 6, 3, 5, 4, 1])

#### 操作

In [3]:
x = torch.randn(5, 3)
y = torch.randn(5,3)
x
y
z = x[0, :]
z 
z += 1.
x
a =  x.view(3,5)
a
x
a
x += 1.
a
b = x.reshape(3, 5)
b
x
b += 1.
x
c = x.clone().view(15)
c.dim()
c

tensor([[-1.5021,  0.3700, -1.2434],
        [-1.2641,  0.3341, -0.1380],
        [ 1.2290, -1.1187, -0.5861],
        [-0.6914, -0.1367, -1.8566],
        [ 0.2754,  0.8988, -0.7595]])

tensor([[-1.6793, -0.0930,  0.2309],
        [ 0.1451,  0.8055, -0.6148],
        [-0.1142, -0.1126,  1.2458],
        [-1.8728,  0.2861,  0.6433],
        [ 1.6910,  0.8067, -0.9974]])

tensor([-1.5021,  0.3700, -1.2434])

tensor([[-0.5021,  1.3700, -0.2434],
        [-1.2641,  0.3341, -0.1380],
        [ 1.2290, -1.1187, -0.5861],
        [-0.6914, -0.1367, -1.8566],
        [ 0.2754,  0.8988, -0.7595]])

tensor([[-0.5021,  1.3700, -0.2434, -1.2641,  0.3341],
        [-0.1380,  1.2290, -1.1187, -0.5861, -0.6914],
        [-0.1367, -1.8566,  0.2754,  0.8988, -0.7595]])

tensor([[-0.5021,  1.3700, -0.2434],
        [-1.2641,  0.3341, -0.1380],
        [ 1.2290, -1.1187, -0.5861],
        [-0.6914, -0.1367, -1.8566],
        [ 0.2754,  0.8988, -0.7595]])

tensor([[-0.5021,  1.3700, -0.2434, -1.2641,  0.3341],
        [-0.1380,  1.2290, -1.1187, -0.5861, -0.6914],
        [-0.1367, -1.8566,  0.2754,  0.8988, -0.7595]])

tensor([[ 0.4979,  2.3700,  0.7566, -0.2641,  1.3341],
        [ 0.8620,  2.2290, -0.1187,  0.4139,  0.3086],
        [ 0.8633, -0.8566,  1.2754,  1.8988,  0.2405]])

tensor([[ 0.4979,  2.3700,  0.7566, -0.2641,  1.3341],
        [ 0.8620,  2.2290, -0.1187,  0.4139,  0.3086],
        [ 0.8633, -0.8566,  1.2754,  1.8988,  0.2405]])

tensor([[ 0.4979,  2.3700,  0.7566],
        [-0.2641,  1.3341,  0.8620],
        [ 2.2290, -0.1187,  0.4139],
        [ 0.3086,  0.8633, -0.8566],
        [ 1.2754,  1.8988,  0.2405]])

tensor([[1.4979, 3.3700, 1.7566],
        [0.7359, 2.3341, 1.8620],
        [3.2290, 0.8813, 1.4139],
        [1.3086, 1.8633, 0.1434],
        [2.2754, 2.8988, 1.2405]])

1

tensor([1.4979, 3.3700, 1.7566, 0.7359, 2.3341, 1.8620, 3.2290, 0.8813, 1.4139,
        1.3086, 1.8633, 0.1434, 2.2754, 2.8988, 1.2405])

In [6]:
x = torch.tensor(1.)
x
x.dim()
x.shape
x.item()
x.numpy()

tensor(1.)

0

torch.Size([])

1.0

array(1., dtype=float32)

In [7]:
x = torch.full((3, 3), 3.)

In [11]:
torch.trace(x).item()

9.0

In [12]:
torch.diag(x)

tensor([3., 3., 3.])

In [13]:
torch.triu(x)

tensor([[3., 3., 3.],
        [0., 3., 3.],
        [0., 0., 3.]])

In [15]:
help(torch.triu)

Help on built-in function triu:

triu(...)
    triu(input, diagonal=0, out=None) -> Tensor
    
    Returns the upper triangular part of a matrix (2-D tensor) or batch of matrices
    :attr:`input`, the other elements of the result tensor :attr:`out` are set to 0.
    
    The upper triangular part of the matrix is defined as the elements on and
    above the diagonal.
    
    The argument :attr:`diagonal` controls which diagonal to consider. If
    :attr:`diagonal` = 0, all elements on and below the main diagonal are
    retained. A positive value excludes just as many diagonals above the main
    diagonal, and similarly a negative value includes just as many diagonals below
    the main diagonal. The main diagonal are the set of indices
    :math:`\lbrace (i, i) \rbrace` for :math:`i \in [0, \min\{d_{1}, d_{2}\} - 1]` where
    :math:`d_{1}, d_{2}` are the dimensions of the matrix.
    
    Args:
        input (Tensor): the input tensor.
        diagonal (int, optional): the diagona

In [16]:
torch.triu(x, diagonal=1)

tensor([[0., 3., 3.],
        [0., 0., 3.],
        [0., 0., 0.]])

In [18]:
torch.tril(x, diagonal=-1)

tensor([[0., 0., 0.],
        [3., 0., 0.],
        [3., 3., 0.]])

In [20]:
help(torch.bmm)

Help on built-in function bmm:

bmm(...)
    bmm(input, mat2, out=None) -> Tensor
    
    Performs a batch matrix-matrix product of matrices stored in :attr:`input`
    and :attr:`mat2`.
    
    :attr:`input` and :attr:`mat2` must be 3-D tensors each containing
    the same number of matrices.
    
    If :attr:`input` is a :math:`(b \times n \times m)` tensor, :attr:`mat2` is a
    :math:`(b \times m \times p)` tensor, :attr:`out` will be a
    :math:`(b \times n \times p)` tensor.
    
    .. math::
        \text{out}_i = \text{input}_i \mathbin{@} \text{mat2}_i
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
              For broadcasting matrix products, see :func:`torch.matmul`.
    
    Args:
        input (Tensor): the first batch of matrices to be multiplied
        mat2 (Tensor): the second batch of matrices to be multiplied
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> input = torch.randn(10, 3, 4

In [21]:
x = torch.rand(128, 45, 56)
y = torch.rand(128, 56, 10)
# x bmm y => (128, 45, 10)
torch.bmm(x, y).shape

torch.Size([128, 45, 10])

In [30]:
help(torch.randint)

Help on built-in function randint:

randint(...)
    randint(low=0, high, size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random integers generated uniformly
    between :attr:`low` (inclusive) and :attr:`high` (exclusive).
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    .. note:
        With the global dtype default (``torch.float32``), this function returns
        a tensor with dtype ``torch.int64``.
    
    Args:
        low (int, optional): Lowest integer to be drawn from the distribution. Default: 0.
        high (int): One above the highest integer to be drawn from the distribution.
        size (tuple): a tuple defining the shape of the output tensor.
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :

In [36]:
x = torch.randint(0, 100, (3, 4))
x
torch.t(x)
x
x.t()
x
x.t_()
x

tensor([[21, 42, 81, 75],
        [84, 55, 42, 62],
        [91, 89, 62, 49]])

tensor([[21, 84, 91],
        [42, 55, 89],
        [81, 42, 62],
        [75, 62, 49]])

tensor([[21, 42, 81, 75],
        [84, 55, 42, 62],
        [91, 89, 62, 49]])

tensor([[21, 84, 91],
        [42, 55, 89],
        [81, 42, 62],
        [75, 62, 49]])

tensor([[21, 42, 81, 75],
        [84, 55, 42, 62],
        [91, 89, 62, 49]])

tensor([[21, 84, 91],
        [42, 55, 89],
        [81, 42, 62],
        [75, 62, 49]])

tensor([[21, 84, 91],
        [42, 55, 89],
        [81, 42, 62],
        [75, 62, 49]])

In [39]:
x = torch.eye(5)
x
torch.inverse(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

tensor([[1., 0., 0., 0., -0.],
        [0., 1., 0., 0., -0.],
        [0., 0., 1., 0., -0.],
        [0., 0., 0., 1., -0.],
        [0., 0., 0., 0., 1.]])

In [41]:
y = torch.randn(5, 5)
y
torch.inverse(y)

tensor([[ 1.0977, -1.3256, -0.9236,  1.2527, -2.1494],
        [ 0.6247,  0.6490,  0.4926, -1.0789,  0.9728],
        [-0.5222, -1.6344,  1.8162, -1.6200, -0.3420],
        [-0.9933,  0.9850, -1.7034, -1.5324,  0.3889],
        [-0.0337, -0.7669,  1.8041, -0.7126, -0.9463]])

tensor([[ 0.3580,  0.7262, -0.0311, -0.1343, -0.1106],
        [-0.1700,  0.0627, -0.7001,  0.1930,  0.7829],
        [-0.2137, -0.0315, -0.1556, -0.1889,  0.4317],
        [-0.1473, -0.3611, -0.1578, -0.3034, -0.1043],
        [-0.1716,  0.1353,  0.3908, -0.2833, -0.7856]])

In [42]:
z = torch.randn(4,3)
z
torch.inverse(z)

tensor([[-0.3966, -0.3416, -0.4643],
        [-1.4352, -0.2513,  0.0960],
        [ 0.0291,  0.3043,  0.8332],
        [ 0.2177, -0.9424, -2.6561]])

RuntimeError: A must be batches of square matrices, but they are 3 by 4 matrices

In [46]:
x = torch.randn(3, 4)
y = torch.randn(3, 4)
z = torch.dot(x, y)
z

RuntimeError: 1D tensors expected, got 2D, 2D tensors at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:774

In [45]:
help(torch.dot)

Help on built-in function dot:

dot(...)
    dot(input, tensor) -> Tensor
    
    Computes the dot product (inner product) of two tensors.
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
    
    Example::
    
        >>> torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
        tensor(7)



In [49]:
x = torch.tensor([3, 4])
y = torch.tensor([3, 4])
z = torch.dot(x, y)
z.item()

25

In [52]:
x = torch.randn(3, 4)
y = torch.randn(3, 4)
z = torch.cross(x, y)
z

tensor([[ 1.2803,  0.8744,  1.2867,  0.7778],
        [ 0.0542, -2.3756,  0.3147, -0.8595],
        [-5.1516, -0.6219,  1.0926,  0.9453]])

In [51]:
help(torch.cross)

Help on built-in function cross:

cross(...)
    cross(input, other, dim=-1, out=None) -> Tensor
    
    
    Returns the cross product of vectors in dimension :attr:`dim` of :attr:`input`
    and :attr:`other`.
    
    :attr:`input` and :attr:`other` must have the same size, and the size of their
    :attr:`dim` dimension should be 3.
    
    If :attr:`dim` is not given, it defaults to the first dimension found with the
    size 3.
    
    Args:
        input (Tensor): the input tensor.
        other (Tensor): the second input tensor
        dim  (int, optional): the dimension to take the cross-product in.
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> a = torch.randn(4, 3)
        >>> a
        tensor([[-0.3956,  1.1455,  1.6895],
                [-0.5849,  1.3672,  0.3599],
                [-1.1626,  0.7180, -0.0521],
                [-0.1339,  0.9902, -2.0225]])
        >>> b = torch.randn(4, 3)
        >>> b
        tensor([[-0.0257, -1.

In [53]:
help(torch.svd)

Help on built-in function svd:

svd(...)
    svd(input, some=True, compute_uv=True, out=None) -> (Tensor, Tensor, Tensor)
    
    This function returns a namedtuple ``(U, S, V)`` which is the singular value
    decomposition of a input real matrix or batches of real matrices :attr:`input` such that
    :math:`input = U \times diag(S) \times V^T`.
    
    If :attr:`some` is ``True`` (default), the method returns the reduced singular value decomposition
    i.e., if the last two dimensions of :attr:`input` are ``m`` and ``n``, then the returned
    `U` and `V` matrices will contain only :math:`min(n, m)` orthonormal columns.
    
    If :attr:`compute_uv` is ``False``, the returned `U` and `V` matrices will be zero matrices
    of shape :math:`(m \times m)` and :math:`(n \times n)` respectively. :attr:`some` will be ignored here.
    
    .. note:: The implementation of SVD on CPU uses the LAPACK routine `?gesdd` (a divide-and-conquer
              algorithm) instead of `?gesvd` for sp

#### 广播机制

In [54]:
x = torch.arange(1, 3).view(1, 2)
x

tensor([[1, 2]])

In [56]:
y = torch.arange(1, 4).view(3, 1)
y

tensor([[1],
        [2],
        [3]])

In [57]:
x+y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

In [59]:
x =[[1, 2],
   [1, 2],
   [1, 2]]
y =[[1, 1],
   [2, 2],
   [3, 3]]
x+y #???
torch.tensor(x)+torch.tensor(y)

[[1, 2], [1, 2], [1, 2], [1, 1], [2, 2], [3, 3]]

tensor([[2, 3],
        [3, 4],
        [4, 5]])

#### 运算的内存开销

In [60]:
x = 1.
y = 2.
before_id = id(y)
y = x +y
id(y) == before_id

False

In [61]:
x = 1.
y = 2.
before_id = id(y)
y += x
id(y) == before_id

False

In [62]:
x = torch.tensor(1.)
y = torch.tensor(2.)
before_id = id(y)
y += x
id(y) == before_id

True

In [63]:
x = torch.tensor(1.)
y = torch.tensor(2.)
before_id = id(y)
torch.add(x, y, y)
id(y) == before_id

tensor(5.)

True

#### Tensor和NumPy相互转换

In [66]:
a = torch.ones(5,5)
b = a.numpy()
a
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

#### Tensor on GPU

In [74]:
if torch.cuda.is_available():
    if torch.cuda.device_count() >1:
        print("cuda device number is:", torch.cuda.device_count())
    else:
        device = torch.device("cuda")          
        device
        dir(device)
        print(device.index)

device(type='cuda')

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'index',
 'type']

None
<method-wrapper '__str__' of torch.device object at 0x7f2ec12d0f78>


In [75]:
x = torch.randn(123, 456, 789)
x.cuda()

tensor([[[-0.2942, -2.5035,  1.5652,  ..., -1.3593,  0.2733, -0.5239],
         [-0.7564, -0.3513, -0.4343,  ...,  0.0948, -0.2034, -1.4703],
         [-1.1445,  1.7627, -1.3090,  ...,  0.7534, -1.8149,  1.1744],
         ...,
         [ 0.0540, -0.2093, -1.1404,  ...,  0.2720,  0.3714,  1.1082],
         [ 0.9434,  0.5345, -0.0240,  ...,  0.6751,  0.1406,  0.2292],
         [ 0.1712, -0.1768, -0.3959,  ...,  0.9342,  0.6442, -0.9732]],

        [[-0.3481, -0.1899,  0.1072,  ...,  0.4036,  0.1830,  2.5561],
         [-0.6004,  0.7683,  1.0864,  ...,  1.5991, -0.5551,  1.0962],
         [-0.4070, -0.8509,  0.9666,  ...,  0.3480, -0.4143, -0.6525],
         ...,
         [-0.8973,  0.8725, -0.1977,  ..., -1.3398, -0.9511,  1.0036],
         [-0.3268,  0.8981,  0.5927,  ...,  1.2937, -1.4522, -1.3546],
         [ 1.1012,  2.0798, -0.0974,  ...,  0.4860,  0.3893,  1.1060]],

        [[ 1.6711,  0.5573, -0.9266,  ...,  0.8801,  0.0031, -0.1855],
         [-1.2166,  0.0368, -1.3721,  ...,  1

In [77]:
y = torch.randint(1, 5, (2, 2))
y.to(device)

tensor([[2, 3],
        [4, 3]], device='cuda:0')

In [78]:
cpu_device = torch.device('cpu') 
y.to(cpu_device)

tensor([[2, 3],
        [4, 3]])

### 自动求梯度(导数)

In [88]:
import torch

# y = a**2*x + b*x + c
# x = 4, a = 3, b=2, c=5

# dy/da = 2*a*x = 2*3*4 =24
# dy/db = x = 4
# dy/dc = 1
x = torch.tensor(4.)
a = torch.tensor(3., requires_grad=True)
b = torch.tensor(2., requires_grad=True)
c = torch.tensor(5., requires_grad=True)


y = a**2*x + b*x + c

a.grad, b.grad, c.grad

torch.autograd.grad(y, [a, b, c])
# grads[0]
# grads[1]
# grads[2]




(None, None, None)

(tensor(24.), tensor(4.), tensor(1.))

#### 概念
Tensor是这个包的核心类，如果将其属性.requires_grad设置为True，它将开始追踪(track)在其上的所有操作（这样就可以利用链式法则进行梯度传播了）。完成计算后，可以调用.backward()来完成所有梯度计算。此Tensor的梯度将累积到.grad属性中。

In [102]:
 y = torch.tensor(3., requires_grad=True)

In [103]:
y = y + 5.
y

tensor(8., grad_fn=<AddBackward0>)

In [104]:
y.backward()
print(y.grad)

None
